# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created: Wed Jun 18 00:37:26 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mnwMain(object):
    def setupUi(self, mnwMain):
        mnwMain.setObjectName(_fromUtf8("mnwMain"))
        mnwMain.setEnabled(True)
        mnwMain.resize(669, 386)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mnwMain.sizePolicy().hasHeightForWidth())
        mnwMain.setSizePolicy(sizePolicy)
        mnwMain.setFocusPolicy(QtCore.Qt.NoFocus)
        mnwMain.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtGui.QWidget(mnwMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnApplyAppChanges = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnApplyAppChanges.setIcon(icon)
        self.btnApplyAppChanges.setObjectName(_fromUtf8("btnApplyAppChanges"))
        self.gridLayout_3.addWidget(self.btnApplyAppChanges, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSecurity = QtGui.QWidget()
        self.tabSecurity.setObjectName(_fromUtf8("tabSecurity"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabSecurity)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gbxSystemwideEncryption = QtGui.QGroupBox(self.tabSecurity)
        self.gbxSystemwideEncryption.setObjectName(_fromUtf8("gbxSystemwideEncryption"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbxSystemwideEncryption)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnChangeRootPassword = QtGui.QToolButton(self.gbxSystemwideEncryption)
        self.btnChangeRootPassword.setIconSize(QtCore.QSize(24, 24))
        self.btnChangeRootPassword.setObjectName(_fromUtf8("btnChangeRootPassword"))
        self.gridLayout_4.addWidget(self.btnChangeRootPassword, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.chkEncryptedRootPartition = QtGui.QCheckBox(self.gbxSystemwideEncryption)
        self.chkEncryptedRootPartition.setObjectName(_fromUtf8("chkEncryptedRootPartition"))
        self.gridLayout_4.addWidget(self.chkEncryptedRootPartition, 1, 0, 1, 1)
        self.chkRootKeyTD = QtGui.QCheckBox(self.gbxSystemwideEncryption)
        self.chkRootKeyTD.setObjectName(_fromUtf8("chkRootKeyTD"))
        self.gridLayout_4.addWidget(self.chkRootKeyTD, 3, 0, 1, 2)
        self.btnChooseRootKeyTD = QtGui.QToolButton(self.gbxSystemwideEncryption)
        self.btnChooseRootKeyTD.setEnabled(True)
        self.btnChooseRootKeyTD.setIconSize(QtCore.QSize(24, 24))
        self.btnChooseRootKeyTD.setAutoRaise(False)
        self.btnChooseRootKeyTD.setObjectName(_fromUtf8("btnChooseRootKeyTD"))
        self.gridLayout_4.addWidget(self.btnChooseRootKeyTD, 3, 2, 1, 1)
        self.gridLayout_7.addWidget(self.gbxSystemwideEncryption, 0, 0, 1, 1)
        self.gbxTamperResistance = QtGui.QGroupBox(self.tabSecurity)
        self.gbxTamperResistance.setObjectName(_fromUtf8("gbxTamperResistance"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gbxTamperResistance)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.chkKernelSignedInTriplicate = QtGui.QCheckBox(self.gbxTamperResistance)
        self.chkKernelSignedInTriplicate.setMinimumSize(QtCore.QSize(0, 0))
        self.chkKernelSignedInTriplicate.setObjectName(_fromUtf8("chkKernelSignedInTriplicate"))
        self.gridLayout_6.addWidget(self.chkKernelSignedInTriplicate, 0, 0, 1, 2)
        self.chkUseDuressPassword = QtGui.QCheckBox(self.gbxTamperResistance)
        self.chkUseDuressPassword.setMinimumSize(QtCore.QSize(0, 0))
        self.chkUseDuressPassword.setObjectName(_fromUtf8("chkUseDuressPassword"))
        self.gridLayout_6.addWidget(self.chkUseDuressPassword, 3, 0, 1, 1)
        self.chkHardwareIsWhitelisted = QtGui.QCheckBox(self.gbxTamperResistance)
        self.chkHardwareIsWhitelisted.setMinimumSize(QtCore.QSize(0, 0))
        self.chkHardwareIsWhitelisted.setObjectName(_fromUtf8("chkHardwareIsWhitelisted"))
        self.gridLayout_6.addWidget(self.chkHardwareIsWhitelisted, 1, 0, 1, 1)
        self.btnChangeDuressPassword = QtGui.QToolButton(self.gbxTamperResistance)
        self.btnChangeDuressPassword.setIconSize(QtCore.QSize(24, 24))
        self.btnChangeDuressPassword.setObjectName(_fromUtf8("btnChangeDuressPassword"))
        self.gridLayout_6.addWidget(self.btnChangeDuressPassword, 3, 1, 1, 1)
        self.btnRegenerateWhitelist = QtGui.QToolButton(self.gbxTamperResistance)
        self.btnRegenerateWhitelist.setObjectName(_fromUtf8("btnRegenerateWhitelist"))
        self.gridLayout_6.addWidget(self.btnRegenerateWhitelist, 1, 1, 1, 1)
        self.chkObfuscateFilesystemMarkers = QtGui.QCheckBox(self.gbxTamperResistance)
        self.chkObfuscateFilesystemMarkers.setMinimumSize(QtCore.QSize(0, 0))
        self.chkObfuscateFilesystemMarkers.setObjectName(_fromUtf8("chkObfuscateFilesystemMarkers"))
        self.gridLayout_6.addWidget(self.chkObfuscateFilesystemMarkers, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.gbxTamperResistance, 1, 0, 1, 1)
        self.gbxForTheParanoid = QtGui.QGroupBox(self.tabSecurity)
        self.gbxForTheParanoid.setObjectName(_fromUtf8("gbxForTheParanoid"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gbxForTheParanoid)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.chkStoreFreenetAndI2pOnHome = QtGui.QCheckBox(self.gbxForTheParanoid)
        self.chkStoreFreenetAndI2pOnHome.setObjectName(_fromUtf8("chkStoreFreenetAndI2pOnHome"))
        self.gridLayout_8.addWidget(self.chkStoreFreenetAndI2pOnHome, 1, 0, 1, 3)
        self.chkUseDropboxWhenEncryptingHome = QtGui.QCheckBox(self.gbxForTheParanoid)
        self.chkUseDropboxWhenEncryptingHome.setObjectName(_fromUtf8("chkUseDropboxWhenEncryptingHome"))
        self.gridLayout_8.addWidget(self.chkUseDropboxWhenEncryptingHome, 0, 0, 1, 3)
        self.spiNoofPanicPushesRequired = QtGui.QSpinBox(self.gbxForTheParanoid)
        self.spiNoofPanicPushesRequired.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.spiNoofPanicPushesRequired.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spiNoofPanicPushesRequired.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spiNoofPanicPushesRequired.setMinimum(3)
        self.spiNoofPanicPushesRequired.setMaximum(20)
        self.spiNoofPanicPushesRequired.setObjectName(_fromUtf8("spiNoofPanicPushesRequired"))
        self.gridLayout_8.addWidget(self.spiNoofPanicPushesRequired, 2, 2, 1, 1)
        self.chkPanicButton = QtGui.QCheckBox(self.gbxForTheParanoid)
        self.chkPanicButton.setObjectName(_fromUtf8("chkPanicButton"))
        self.gridLayout_8.addWidget(self.chkPanicButton, 2, 0, 1, 2)
        self.gridLayout_7.addWidget(self.gbxForTheParanoid, 1, 1, 1, 1)
        self.gbxHomeEncryption = QtGui.QGroupBox(self.tabSecurity)
        self.gbxHomeEncryption.setObjectName(_fromUtf8("gbxHomeEncryption"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gbxHomeEncryption)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnChangeHomePassword = QtGui.QToolButton(self.gbxHomeEncryption)
        self.btnChangeHomePassword.setIconSize(QtCore.QSize(24, 24))
        self.btnChangeHomePassword.setObjectName(_fromUtf8("btnChangeHomePassword"))
        self.gridLayout_5.addWidget(self.btnChangeHomePassword, 4, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 4, 2, 1, 1)
        self.chkEncryptedHomePartition = QtGui.QCheckBox(self.gbxHomeEncryption)
        self.chkEncryptedHomePartition.setObjectName(_fromUtf8("chkEncryptedHomePartition"))
        self.gridLayout_5.addWidget(self.chkEncryptedHomePartition, 4, 1, 1, 1)
        self.btnChooseHomeKeyTD = QtGui.QToolButton(self.gbxHomeEncryption)
        self.btnChooseHomeKeyTD.setObjectName(_fromUtf8("btnChooseHomeKeyTD"))
        self.gridLayout_5.addWidget(self.btnChooseHomeKeyTD, 5, 3, 1, 1)
        self.chkHomeKeyTD = QtGui.QCheckBox(self.gbxHomeEncryption)
        self.chkHomeKeyTD.setObjectName(_fromUtf8("chkHomeKeyTD"))
        self.gridLayout_5.addWidget(self.chkHomeKeyTD, 5, 1, 1, 2)
        self.gridLayout_7.addWidget(self.gbxHomeEncryption, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tabSecurity, _fromUtf8(""))
        self.tabGreeter = QtGui.QWidget()
        self.tabGreeter.setObjectName(_fromUtf8("tabGreeter"))
        self.gridLayout = QtGui.QGridLayout(self.tabGreeter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnResetLxdmSettings = QtGui.QPushButton(self.tabGreeter)
        self.btnResetLxdmSettings.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnResetLxdmSettings.setIcon(icon1)
        self.btnResetLxdmSettings.setObjectName(_fromUtf8("btnResetLxdmSettings"))
        self.gridLayout.addWidget(self.btnResetLxdmSettings, 3, 4, 1, 1)
        self.pteLxdmSettings = QtGui.QPlainTextEdit(self.tabGreeter)
        self.pteLxdmSettings.setObjectName(_fromUtf8("pteLxdmSettings"))
        self.gridLayout.addWidget(self.pteLxdmSettings, 2, 0, 1, 5)
        self.label_2 = QtGui.QLabel(self.tabGreeter)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 4)
        self.tabWidget.addTab(self.tabGreeter, _fromUtf8(""))
        self.tabAdvanced = QtGui.QWidget()
        self.tabAdvanced.setObjectName(_fromUtf8("tabAdvanced"))
        self.tabWidget.addTab(self.tabAdvanced, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.btnExitWithoutSaving = QtGui.QPushButton(self.centralwidget)
        self.btnExitWithoutSaving.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/filequit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExitWithoutSaving.setIcon(icon2)
        self.btnExitWithoutSaving.setObjectName(_fromUtf8("btnExitWithoutSaving"))
        self.gridLayout_3.addWidget(self.btnExitWithoutSaving, 1, 2, 1, 1)
        self.btnResetAll = QtGui.QPushButton(self.centralwidget)
        self.btnResetAll.setIcon(icon1)
        self.btnResetAll.setIconSize(QtCore.QSize(18, 19))
        self.btnResetAll.setObjectName(_fromUtf8("btnResetAll"))
        self.gridLayout_3.addWidget(self.btnResetAll, 1, 1, 1, 1)
        mnwMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(mnwMain)
        self.statusbar.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mnwMain.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(mnwMain)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionChangePwDisk = QtGui.QAction(mnwMain)
        self.actionChangePwDisk.setObjectName(_fromUtf8("actionChangePwDisk"))
        self.actionChangePwRoot = QtGui.QAction(mnwMain)
        self.actionChangePwRoot.setObjectName(_fromUtf8("actionChangePwRoot"))
        self.actionChangePwBoom = QtGui.QAction(mnwMain)
        self.actionChangePwBoom.setObjectName(_fromUtf8("actionChangePwBoom"))
        self.actionDecrypt = QtGui.QAction(mnwMain)
        self.actionDecrypt.setObjectName(_fromUtf8("actionDecrypt"))
        self.actionWhitelist_ON = QtGui.QAction(mnwMain)
        self.actionWhitelist_ON.setObjectName(_fromUtf8("actionWhitelist_ON"))
        self.actionEncryption = QtGui.QAction(mnwMain)
        self.actionEncryption.setObjectName(_fromUtf8("actionEncryption"))
        self.actionWhitelist = QtGui.QAction(mnwMain)
        self.actionWhitelist.setCheckable(False)
        self.actionWhitelist.setObjectName(_fromUtf8("actionWhitelist"))
        self.actionObfuscation = QtGui.QAction(mnwMain)
        self.actionObfuscation.setObjectName(_fromUtf8("actionObfuscation"))
        self.actionBoot_Settings = QtGui.QAction(mnwMain)
        self.actionBoot_Settings.setObjectName(_fromUtf8("actionBoot_Settings"))

        self.retranslateUi(mnwMain)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mnwMain)

    def retranslateUi(self, mnwMain):
        mnwMain.setWindowTitle(_translate("mnwMain", "Chrubix", None))
        self.btnApplyAppChanges.setText(_translate("mnwMain", "Apply Changes", None))
        self.gbxSystemwideEncryption.setTitle(_translate("mnwMain", "Systemwide Encryption", None))
        self.btnChangeRootPassword.setToolTip(_translate("mnwMain", "Change root password", None))
        self.btnChangeRootPassword.setStatusTip(_translate("mnwMain", "Click here to change the root partition\'s password", None))
        self.btnChangeRootPassword.setText(_translate("mnwMain", "...", None))
        self.chkEncryptedRootPartition.setText(_translate("mnwMain", "Encrypted root partition", None))
        self.chkRootKeyTD.setText(_translate("mnwMain", "Store part of key on thumb drive", None))
        self.btnChooseRootKeyTD.setToolTip(_translate("mnwMain", "Choose the thumb drive", None))
        self.btnChooseRootKeyTD.setStatusTip(_translate("mnwMain", "Insert a thumb drive and click the button to choose the new thumb drive", None))
        self.btnChooseRootKeyTD.setText(_translate("mnwMain", "...", None))
        self.gbxTamperResistance.setTitle(_translate("mnwMain", "Tamper Resistance", None))
        self.chkKernelSignedInTriplicate.setText(_translate("mnwMain", "Kernel is signed in triplicate", None))
        self.chkUseDuressPassword.setToolTip(_translate("mnwMain", "Duress password will nuke disk", None))
        self.chkUseDuressPassword.setStatusTip(_translate("mnwMain", "To nuke the home partition suerreptisiously, prefix/postfix real password with duress password", None))
        self.chkUseDuressPassword.setText(_translate("mnwMain", "Duress password", None))
        self.chkHardwareIsWhitelisted.setText(_translate("mnwMain", "Hardware is whitelisted", None))
        self.btnChangeDuressPassword.setText(_translate("mnwMain", "...", None))
        self.btnRegenerateWhitelist.setToolTip(_translate("mnwMain", "Regenerate whitelist", None))
        self.btnRegenerateWhitelist.setStatusTip(_translate("mnwMain", "Accept all currently connected devices in future. All others are rejected at boot-time.", None))
        self.btnRegenerateWhitelist.setText(_translate("mnwMain", "...", None))
        self.chkObfuscateFilesystemMarkers.setText(_translate("mnwMain", "Obfuscate filesystem markers", None))
        self.gbxForTheParanoid.setTitle(_translate("mnwMain", "For the Paranoid", None))
        self.chkStoreFreenetAndI2pOnHome.setText(_translate("mnwMain", "Store Freenet and I2P on home partition", None))
        self.chkUseDropboxWhenEncryptingHome.setText(_translate("mnwMain", "Store part of the home key online", None))
        self.spiNoofPanicPushesRequired.setSuffix(_translate("mnwMain", " pushes", None))
        self.spiNoofPanicPushesRequired.setPrefix(_translate("mnwMain", "takes ", None))
        self.chkPanicButton.setToolTip(_translate("mnwMain", "Power button doubles as a panic button", None))
        self.chkPanicButton.setStatusTip(_translate("mnwMain", "To nuke the laptop\'s disk, push the Power button N times in as many seconds", None))
        self.chkPanicButton.setText(_translate("mnwMain", "Panic button", None))
        self.gbxHomeEncryption.setTitle(_translate("mnwMain", "Home Encryption", None))
        self.btnChangeHomePassword.setToolTip(_translate("mnwMain", "Change home password", None))
        self.btnChangeHomePassword.setStatusTip(_translate("mnwMain", "Click here to change the home partition\'s password", None))
        self.btnChangeHomePassword.setText(_translate("mnwMain", "...", None))
        self.chkEncryptedHomePartition.setText(_translate("mnwMain", "Encrypted home partition", None))
        self.btnChooseHomeKeyTD.setText(_translate("mnwMain", "...", None))
        self.chkHomeKeyTD.setText(_translate("mnwMain", "Store part of key on thumb drive", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSecurity), _translate("mnwMain", "Security", None))
        self.btnResetLxdmSettings.setText(_translate("mnwMain", "Reset", None))
        self.pteLxdmSettings.setPlainText(_translate("mnwMain", "\n"
"", None))
        self.label_2.setText(_translate("mnwMain", "Greeter Configuration File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGreeter), _translate("mnwMain", "Greeter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvanced), _translate("mnwMain", "Advanced", None))
        self.btnExitWithoutSaving.setText(_translate("mnwMain", "Lose Changes && Exit", None))
        self.btnResetAll.setText(_translate("mnwMain", "Reset", None))
        self.actionExit.setText(_translate("mnwMain", "Exit", None))
        self.actionChangePwDisk.setText(_translate("mnwMain", "Disk", None))
        self.actionChangePwRoot.setText(_translate("mnwMain", "Root", None))
        self.actionChangePwBoom.setText(_translate("mnwMain", "Boom", None))
        self.actionDecrypt.setText(_translate("mnwMain", "Decrypt Disk", None))
        self.actionWhitelist_ON.setText(_translate("mnwMain", "Create Whitelist", None))
        self.actionEncryption.setText(_translate("mnwMain", "Decrypt Root Partition", None))
        self.actionWhitelist.setText(_translate("mnwMain", "Hardware Whitelist", None))
        self.actionObfuscation.setText(_translate("mnwMain", "Obfuscate Filesystem", None))
        self.actionBoot_Settings.setText(_translate("mnwMain", "Boot Settings", None))

import resources_rc
